Repository SOLUX-h-APP-y/backend, pull requests merged in 2025-01, with the labels that each got.

#3 [Init] spring boot init 및 mysql 연결
  .gitignore
  .metadata/.lock
  bilingServer/.gitattributes
  bilingServer/.gitignore
  bilingServer/build.gradle
  bilingServer/gradle/wrapper/gradle-wrapper.jar
  bilingServer/gradle/wrapper/gradle-wrapper.properties
  bilingServer/gradlew
  bilingServer/gradlew.bat
  bilingServer/settings.gradle
  bilingServer/src/main/java/com/happy/biling/BilingServerApplication.java
  bilingServer/src/main/resources/schema.sql
  bilingServer/src/test/java/com/happy/biling/BilingServerApplicationTests.java
Labels: chore

#4 [Feat] Entity 생성
  bilingServer/src/main/java/com/happy/biling/domain/entity/ChatMessage.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/ChatRoom.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/Post.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/PostImage.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/Review.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/User.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Category.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Distance.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/PostStatus.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/PostType.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Tier.java
Labels: feat

#7 [Chore] .project 파일 생성
  .project
Labels: chore

#8 [Test] spring sequrity login폼 삭제 및 연동 테스트용 임시 보안 약화
  bilingServer/src/main/java/com/happy/biling/config/SecurityConfig.java
Labels: test

#9 [Feat] 대여글 작성 API 구현 (이미지 불포함)
  bilingServer/src/main/java/com/happy/biling/controller/PostController.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/PostRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/UserRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/PostService.java
  bilingServer/src/main/java/com/happy/biling/dto/post/PostWriteRequestDto.java
Labels: feat

#10 [FEAT] 닉네임 중복 검사 API 구현
  bilingServer/src/main/java/com/happy/biling/controller/UserConroller.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/UserRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/UserService.java
  bilingServer/src/main/java/com/happy/biling/dto/auth/NicknameCheckRequestDto.java
Labels: feat

#15 [Feat] 카카오 로그인/회원가입 구현
  bilingServer/build.gradle
  bilingServer/src/main/java/com/happy/biling/config/SecurityConfig.java
  bilingServer/src/main/java/com/happy/biling/controller/KakaoLoginController.java
  bilingServer/src/main/java/com/happy/biling/controller/KakaoLoginPageController.java
  bilingServer/src/main/java/com/happy/biling/controller/UserConroller.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/User.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/UserRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/KaKaoService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/PostService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/UserService.java
  bilingServer/src/main/java/com/happy/biling/dto/auth/KakaoLoginResponseDto.java
  bilingServer/src/main/java/com/happy/biling/dto/auth/KakaoTokenResponseDto.java
  bilingServer/src/main/java/com/happy/biling/dto/auth/KakaoUserInfoResponseDto.java
  bilingServer/src/main/java/com/happy/biling/dto/auth/SignUpRequestDto.java
  bilingServer/src/main/java/com/happy/biling/dto/auth/TokenResponseDto.java
  bilingServer/src/main/java/com/happy/biling/security/JwtAuthentication.java
  bilingServer/src/main/java/com/happy/biling/security/JwtAuthenticationFilter.java
  bilingServer/src/main/java/com/happy/biling/security/JwtUtil.java
  bilingServer/src/main/resources/schema.sql
  bilingServer/src/main/resources/static/kakao_login_medium_narrow.png
  bilingServer/src/main/resources/templates/login.html
Labels: feat

#14 [FEAT] 리뷰 작성 API 구현
  bilingServer/build.gradle
  bilingServer/gradlew
  bilingServer/src/main/java/com/happy/biling/config/SecurityConfig.java
  bilingServer/src/main/java/com/happy/biling/controller/PostController.java
  bilingServer/src/main/java/com/happy/biling/controller/ReviewController.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/Post.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Category.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Distance.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/PostStatus.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Tier.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/ReviewRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/PostService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ReviewService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/UserService.java
  bilingServer/src/main/java/com/happy/biling/dto/post/PostWriteRequestDto.java
  bilingServer/src/main/java/com/happy/biling/dto/review/ReviewRequestDto.java
Labels: feat

#30 [Fix] 프로필,리뷰 post 오류 수정
  bilingServer/src/main/java/com/happy/biling/controller/ProfileController.java
  bilingServer/src/main/java/com/happy/biling/controller/ReviewController.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/Cheer.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/Post.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/Distance.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/enums/DistanceConverter.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ProfileService.java
  bilingServer/src/main/java/com/happy/biling/dto/review/ReviewCreateRequestDto.java
Labels: fix

#34 [Feat] aws s3 프로필 이미지 관련 구현
  bilingServer/build.gradle
  bilingServer/src/main/java/com/happy/biling/config/S3Config.java
  bilingServer/src/main/java/com/happy/biling/controller/ProfileController.java
  bilingServer/src/main/java/com/happy/biling/controller/ReviewController.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ProfileService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/S3Uploader.java
  bilingServer/src/main/java/com/happy/biling/dto/profile/ProfileUpdateRequestDto.java
  bilingServer/src/main/resources/application.properties
Labels: feat

#36 [Feat] post 이미지, 응원하기 관련 구현
  bilingServer/src/main/java/com/happy/biling/controller/PostController.java
  bilingServer/src/main/java/com/happy/biling/controller/ProfileController.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/PostImageRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/PostService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ProfileService.java
  bilingServer/src/main/java/com/happy/biling/domain/service/S3Uploader.java
  bilingServer/src/main/java/com/happy/biling/dto/post/PostPreviewResponseDto.java
  bilingServer/src/main/java/com/happy/biling/dto/post/PostWriteRequestDto.java
  bilingServer/src/main/java/com/happy/biling/dto/profile/CheerResponseDto.java
Labels: feat

#39 [FEAT] 쪽지 조회 구현
  bilingServer/src/main/java/com/happy/biling/controller/ChatMessageController.java
  bilingServer/src/main/java/com/happy/biling/controller/ChatRoomController.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/ChatMessage.java
  bilingServer/src/main/java/com/happy/biling/domain/entity/ChatRoom.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/ChatMessageRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/ChatRoomRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ChatMessageService.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/ChatRoomDetailResponse.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/ChatRoomResponse.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/MessageResponse.java
Labels: feat

#43 [FIX] 쪽지 내용 조회시 Post Image 가져오도록 수정
  bilingServer/src/main/java/com/happy/biling/domain/service/ChatMessageService.java
Labels: fix

#44 [Feat] 게시글 삭제/상태 변경 API 구현 및 특정 유저 게시글 목록 가져오기 개선
  bilingServer/src/main/java/com/happy/biling/controller/PostController.java
  bilingServer/src/main/java/com/happy/biling/controller/UserConroller.java
  bilingServer/src/main/java/com/happy/biling/domain/repository/PostImageRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/PostService.java
  bilingServer/src/main/java/com/happy/biling/dto/post/FilteredPostPreviewResponseDto.java
Labels: feat

#45 [FEAT] 쪽지 답장 기능 보완
  bilingServer/src/main/java/com/happy/biling/domain/repository/ChatMessageRepository.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ChatMessageService.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/ChatRoomDetailResponse.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/ChatRoomResponse.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/SendMessageRequest.java
Labels: feat

#46 [FIX] 쪽지 보내기 Response 수정
  bilingServer/src/main/java/com/happy/biling/controller/ChatMessageController.java
  bilingServer/src/main/java/com/happy/biling/domain/service/ChatMessageService.java
  bilingServer/src/main/java/com/happy/biling/dto/chat/SendMessageResponse.java
Labels: fix
